
const Sequelize = require('sequelize');

const sequelize = new Sequelize({
  database: 'PWR_db',
  dialect: 'postgres',
  define: {
    underscored: true, // use underscored column names for columns generated by sequelize (e.g. timestamps as created_at rather than createdAt)
  }
});

const Workout = sequelize.define('workout', {
    name: Sequelize.STRING,
    duration: Sequelize.INTEGER,
    description: Sequelize.STRING,
    difficulty: Sequelize.STRING
});

const Regimen = sequelize.define('regimen', {
    workout_id: Sequelize.INTEGER,
});

Workout.belongsTo(Regimen);
Regimen.hasMany(Workout, {onDelete: 'cascade'});

module.exports = {
  sequelize,
  Workout,
  Regimen
};
